version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: x_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres  # Изменили на 'postgres'
      POSTGRES_PASSWORD: mypassword  # Установите нужный пароль для 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
