version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: x_postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"  # Ограничение доступа только локально
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network
    security_opt:
      - seccomp:default  # Более безопасная политика seccomp
    user: postgres_user  # Указываем непривилегированного пользователя
    secrets:
      - postgres_password  # Использование Docker Secrets для хранения пароля

volumes:
  pgdata:

networks:
  db_network:
    driver: bridge

secrets:
  postgres_password:
    external: true  # Используем внешний секрет
