version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: x_postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Убираем ограничение на локальный хост
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:

networks:
  db_network:
    driver: bridge
